### ISSUE TITLE
Retrieve data from AWS for Old Snapshot Decommissioning

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1082]
Retrieve data to identify snapshots that are older than a time from their creation (e.g., 30 days). Create a recommendation if you find them.

AWS API documentation:
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_Operations.html

**Comment by StefaniaNorisSorint** [comment]
In attesa di revisione comandi da parte del business.

**Comment by anbrenna** [comment]
No needed anymore
