### ISSUE TITLE
Verify Agola behavior when DEV environment  is updated

### ISSUE THREAD

**Issue by cbiglioli** [ercole-io/ercole#1116]
Verify Agola behavior when DEV environment  is updated.

It seems that DEV environment is not accurately updated by Agola. 

Verify if is changes something in order to reactivate Agola's behavior accurately.

**Comment by afumagalli98** [comment]
The bug arose after the user used to authenticate to the docker image was removed.
Solved ignoring the `ocir-secret` and changing the containers registry on oracle cloud to public.

**Comment by afumagalli98** [comment]
Solved the redeploy-service bug using new oci config.
Created new redeploy-service tag named `afumagalli` (because personal access) and pushed on ercole infrastructure.
