### ISSUE TITLE
Create a new API to retrieve AWS objects

### ISSUE THREAD

**Issue by cbiglioli** [ercole-io/ercole#1118]
Create a new API to retrieve AWS objects.

Create e new API to retrieve AWS objects: **/aws/aws-objects** .

To view how to implement it, see the similar API: /oracle-cloud/oci-objects.

The objects to count are:

- ec2
- s3
- load balancer
- ebs
- rds
- vpc
- efs

**Comment by StefaniaNorisSorint** [comment]
Per ciascuna categoria capire quanti oggetti sono configurati.
