### ISSUE TITLE
Add separation of roles on Ercole

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1164]
Different profile of user must see different information on Ercole

**Comment by anbrenna** [comment]
An administration user has to be able to:
- create users
- create groups
- bind an user to a group
- define priviledge for a group (list of pages [menù item] - select the visibility of a single page / location)
- update a user password

A user has to be able to:
- update the password

All the data has to be saved in a new or more collections on DB

**Comment by StefaniaNorisSorint** [comment]
Waiting for functional requirements tbd
