### ISSUE TITLE
Manage data retention ercole server

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole#1196]
Current Host Cleaning Job
Archived Host Cleaning Job
Freshness Check Job

**Comment by cbiglioli** [comment]
The **CurrentHostCleaningJob** job dismisses all active hosts where the creation date is less than the date calculated as follows: the hours present in the `HourThreshold` item of `DataService.CurrentHostCleaningJob` are subtracted from the job execution date. By default this parameter is configured equal to 8760, i.e. one year.

The **ArchivedHostCleaningJob** job deletes all archived hosts where the creation date is less than the date calculated as follows: the hours present in the `HourThreshold` item of `DataService.ArchivedHostCleaningJob` are subtracted from the job execution date. By default this parameter is configured equal to 8760, i.e. one year.

The **FreshnessCheckJob** job does the following:
- 	delete all alerts with code `NO_DATA`
-  	fetch all active hosts
- 	for each active host fetched:
        * the value of the `Period` property of the host is retrieved (if it is less than or equal to zero it is valued with 24) . The `Period` property contains the `hours` value retrieved from the agent (including rhel5) --> `config.json` file. For the perl agent the property name in the `config.json` file is `frequency`.
        * If the creation date of the host is less than the date calculated as follows: the hours of the Period property are subtracted from the job execution date, a `NO_DATA` alert is created
