### ISSUE TITLE
[BUG] - Export data button of service page show mismatch column

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole#1341]
When I export page services i see in excel followin column:
Hostname | DB Name | Name | Failover Method | Failover Type | Failover Retries | Failover Delay | Enabled

I should see only 
Hostname | DB Name | Service Name | Enabled

**Comment by cbiglioli** [comment]
Already implemented with https://github.com/ercole-io/ercole/issues/1221
