### ISSUE TITLE
Rich Hosts search

### ISSUE THREAD

**Issue by mbolis** [ercole-io/ercole#142]
I want to be able to apply richer filters to the /hosts API

More query parameters:
* hostname
* db
* technology
* virtual-platform
* virtual-cluster
* physical-hostname
* os
* kernel
* memory-lte
* memory-gte
* swap-lte
* swap-gte
* is-cluster
* cpu-model
* cpu-vthreads
* cpu-cores

**Comment by amreo** [comment]
technology => assets
