### ISSUE TITLE
Authentication with the Azure SDK

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1432]
Investigate how to integrate in Ercole the Authentication to Microsoft Azure platform.

**Comment by cbiglioli** [comment]
To connect to Microsoft Azure platform via code, therefore via Ercole, you need to have the following information:

**Tenant ID
Client ID
Client Secret**

Example:

`cred, err := azidentity.NewClientSecretCredential("<Tenant ID>", "<Client ID>", "<Client Secret>", nil)`

This way you have the type object *azidentity.ClientSecretCredential to be used later in the various clients.

Each client has a specific task to fetch data from the platform (the real API).

The client may need the **Subscription ID** as a parameter.

Example (retrieve public IP addresses list):

`client, err := armnetwork.NewPublicIPAddressesClient("<Subscription ID>", cred, nil)`

For more information: https://learn.microsoft.com/en-us/rest/api/azure/
