### ISSUE TITLE
Verify RequestSummarizedUsages OCI API

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1433]
Investigate how to use RequestSummarizedUsages API in Ercole when interfacing Oracle Cloud platform.
Refer to the following link:
https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/UsageSummary/RequestSummarizedUsages

**Comment by cbiglioli** [comment]
We need information about both the input parameters the API needs and how the API will be used. However the API can be used within Ercole using the already existing engine.
