### ISSUE TITLE
Generate report (Pdf, ppt, ...) from Ercole

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1439]
Verify how to generate pdf or ppt document from Ercole data.
By example you can use data from license compliance and try to write a pdf or ppt document. 
In the first instance try to generate a ppt document.
Once you close this investigation task open a new one to integrate the procedure in ercole BE.

**Comment by cbiglioli** [comment]
We need an editable file to be generated.

For GO, to create Powerpoint files from templates, we only have this paid solution: https://unidoc.io/post/creating-powerpoint-slides-from-templates/

An alternative could be to create a text file like Word.
