### ISSUE TITLE
Add section to view license dismissed

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole#155]
**Is your feature request related to a problem? Please describe.**
When user go to Host --> Database --> License tab he can disable a specific license. 
This is very helpful for example when there are bugs in Oracle Database. 
Find license dismissed now it's very complicated so there is necessity to semplify it

**Describe the solution you'd like**
One possible solution is to create s specific report page.

**Comment by amreo** [comment]
- [ ] BE implementation
- [ ] FE design 
- [ ] FE implementation

**Comment by amreo** [comment]
The endpoint is GET /license-modifiers (command `ercole api search-license-modifiers`)
