### ISSUE TITLE
Update the Oracle license calculation when secondary is not a RAC

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1606]
Update the secondary licenses calculation on Oracle DB:
- remove check (if db.Dataguard && !db.IsRAC from checkSecondaryDbs funzion in the ercole/data-service/service
/oracle_databases.go
- don't append license in addLicensesToSecondaryDb funztion if the secondary DB !isRAC and license is of RAC type A90619 or L10005

**Comment by afumagalli98** [comment]
In the second point must be added also the license type L76094 and L76084.
