### ISSUE TITLE
Package ercole for debian+ubuntu 18.04+ and add to a ppa(or packagecloud)

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#179]
**Is your feature request related to a problem? Please describe.**
No. Simply I don't want to install ercole downloading the deb from github

**Describe the solution you'd like**
1) Setup CI/CD to build a package for ercole
2) Load the artifact to packagecloud or ppa

**Describe alternatives you've considered**
Install ercole manually

**Comment by cirelli94** [comment]
Won't do for now!
