### ISSUE TITLE
Add support to authentication flow with keycloak, basic auth and ldap

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#180]
**Is your feature request related to a problem? Please describe.**
I don't want to use basic auth as authentication flow, but I want to use a token 

**Describe the solution you'd like**
Implement the OAuth auth flow

**Comment by cirelli94** [comment]
What is CMDS @amreo ? Thanks

**Comment by amreo** [comment]
commands/subcommands

**Comment by anbrenna** [comment]
No longer required
