### ISSUE TITLE
Licenses Consumed seems to be wrongly calculated

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1817]
In the page Licenses Compliance the value of Licenses Consumed seems to be wrong for this Part Numbers:
A90611 (1353)
L47232 (1188)
L27158 (982)
A90649 (1306)
A90622 (495)
L47247 (727)
A90620 (1300)
A90650 (1274)
in brackets is the licence number calculated manually from the licences used

**Comment by afumagalli98** [comment]
The license calculation is right considering the clusters
