### ISSUE TITLE
Add new parameter to GCP recommendation

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#1897]
The API that returns GPC recommendation related to disks has to be enhanced with a new parameters to indicate how will be easy implement the recommendation. 
The average percentage of the values reported in the recommendation should be calculated.
4 range should be defined
- 0-25
- 25-50
- 50-75
- 75-100

**Comment by afumagalli98** [comment]
the resolution level column is not very clear to understand, and must be renamed in "optimization score" and the value is not a string but an integer.
this field is the average of the details values and must be calculated as follows: 

- optimization score = 100 - avg.percentage

change the field name and behavior also in the export API
