### ISSUE TITLE
Alert when Database Oracle is UP but not in oratab

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole#216]
**Is your feature request related to a problem? Please describe.**
Yes when database entry is not in oratab there is no alert 

**Describe the solution you'd like**
Check difference between database UP and database in Oratab, when there are difference create an alert

**Comment by cirelli94** [comment]
agent side we have to check db in execution, e.g. `ps -ef | grep pmon`
server side generate an alert for each DB find but not in oratab: this will need edits to hostdata
