### ISSUE TITLE
Add API to get know if changes about the hostdatas were occurred

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#220]
**Is your feature request related to a problem? Please describe.**
I want to know if the hostdata stored in the database were inserted or changed.

**Describe alternatives you've considered**
We can use the API `GET /hosts?sort-by=CreatedAt&sord-desc=true&page=0&size=1&mode=summary` periodically for getting the _id of the last inserted host. If the _id is not equal than the previous

**Comment by cirelli94** [comment]
Not required.
