### ISSUE TITLE
Create a middleware service to convert old hostdata

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#237]
Create a middleware service to convert old hostdata v0 in hostdata v1 and send it to ercole v2.
It's useful to update gradually old agents and to migrate to ercole v2.

**Comment by mbolis** [comment]
As an alternative, support versioned API. If not modular enough it can get unwieldy, though.

Also consider that, if further incompatible changes to the data structure are made, this kind of API versioning can lead to bloat. New users don't care for backwards compatibility!

**Comment by amreo** [comment]
Ercole already support versioned hostdata through SchemaVersion field

**Comment by cirelli94** [comment]
I have been told this is not needed from business.
