### ISSUE TITLE
Investigate Alert Service functionalities

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#243]
As of now, `/alerts` is in api-service, and read alerts generated from alert-service from the db.

We would like that `/alerts` api do the checks every time is called, of with a cache if checks are slow (e.g. > 0.5s).
To do so we should remove freshnessCheckJob (with various params in config.toml).
We should use a default value of time after that an agent is considered "old": 25h.

Should we receive how often every single agent is set to run from hostdata?

alert-service should expose this api and not api-service?

**Comment by mbolis** [comment]
A cache should be in place in between the API endpoint and the actual data.

Cache configuration should be part of service configuration: cache eviction times are to be decided when the service is started, not each time the cache is polled.

[go-cache](https://github.com/patrickmn/go-cache) is both pretty simple and fits the role well.

**Comment by cirelli94** [comment]
Won't do.
