### ISSUE TITLE
Create chart-service

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#244]
We must create a new chart-service to confine functionalities related to dashboard charts.

![aww-board(1)](https://user-images.githubusercontent.com/1636493/85569024-796c9280-b632-11ea-96f9-b79092b98b1d.png)

We must have an API for each graph that must return array of balls for graph:

- `/technologies?technology=xxx&metrics=yyy`

for now, technology supported is only `Oracle/database` with metrics `work` and `version`

`/technologies?technology=Oracle/database&metrics=work`
size is the number of licenses 
name is model.OracleDatabase.InstanceName
```
{
    "data": [  { "name": "POLPE02", "color": "#FF1234", "size": 42  }, ... ],
    "legend": { "size": "Value of work" }
}

```

`/technologies?technology=Oracle/database&metrics=version`
```
{
    "data": [ { "name": "v5", "color": "#FF1234", "size": 84  }, ... ],
     "legend": { "size": "Number of occurrences" }
}

```

- `/software-types`:
size is the number of licenses for proprietary software
while is the count of instances for opensource technologies.
```
{
    "proprietary-paid": [ { "name": "Oracle/database", "size": 42, "":   }, ... ],
    "proprietary-unpaid": [ { "name": "Oracle/database", "size": 23, "":   }, ... ],
    "opensource": [{ "name": "MariaDB", "size": 42  }, ... ],
     "legend": { "size": "Number of occurrences" }
}
```

- `/changes?date={date}`
size is the actual number of licenses
change is percentual change since {date}
if a new technology has been added, so from zero it became `n`, the change value must be 0
if a technology has been removed, so from `n` it became 0, we should hide it.

```
{
    "data":  [ { "name": "Oracle/database", "size": 42, "",   "change" : "0.45"}, ... ],
    "legend": { "size": "Number of occurrences" }
}

```

- `/type-of-technology`
```
{
    "databases":  [ { "name": "Oracle/database", "size": 42, "":   }, ... ],
    "middlewares":  [ { "name": "Oracle/web-logic", "size": 42, "":   }, ... ],
    "operating-systems": [ { "name": "Red Hat Enterprise Linux", "color": "#FF1234", "size": 42, "":   }, ... ],
    "legend": { "size": "Number of occurrences" }
}
```

**Comment by cirelli94** [comment]
/technologies?technology=Oracle/database&metrics=work -> name: "DBNAME/Hostname"?

**Comment by cirelli94** [comment]
we should add instanceName to model.OracleDatabase and use that.

```
diff --git a/marshal/oracle/database.go b/marshal/oracle/database.go
index dc4e72e..e8640f0 100644
--- a/marshal/oracle/database.go
+++ b/marshal/oracle/database.go
@@ -36,6 +36,7 @@ func Database(cmdOutput []byte) model.OracleDatabase {
 			db.Name = strings.TrimSpace(splitted[0])
 			db.UniqueName = strings.TrimSpace(splitted[1])
 			db.InstanceNumber = marshal.TrimParseInt(splitted[2])
+			db.InstanceName = marshal.TrimParseInt(splitted[2])
 			db.Status = strings.TrimSpace(splitted[3])
 			db.Version = strings.TrimSpace(splitted[4])
 			db.Platform = strings.TrimSpace(splitted[5])
diff --git a/sql/db.sql b/sql/db.sql
index b6c17a4..1d6db4e 100644
--- a/sql/db.sql
+++ b/sql/db.sql
@@ -137,6 +137,8 @@ SELECT
    FROM v$database) AS DB_Unique_name,
   (SELECT instance_number
    FROM v$instance) AS Instance_number,
+  (SELECT instance_name
+   FROM v$instance) AS Instance_name,
   (SELECT status
    FROM v$instance) AS DB_Status, (
                                      (SELECT VERSION
```

**Comment by amreo** [comment]
How is the calculation of /software-types done?

**Comment by cirelli94** [comment]
Me and @amreo have talked about changes value and thought that:
-    if a new technology has been added, so from zero it became n, the change value must be 0
 -   if a technology has been removed, so from n it became 0, we should hide it.

Do you agree @raffaelloferrari ? Do you prefer a different implementation? If so, how should we do this?

**Comment by amreo** [comment]
/software-types is missing because of the lack of calculation algorithm
