### ISSUE TITLE
Add InstanceName to model.OracleDatabase

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#254]
we should add instanceName of type `string` to model.OracleDatabase and in HostData

**Comment by amreo** [comment]
InstanceName == Name????

**Comment by cirelli94** [comment]
InstanceName should be unique, while Name not.
It must be added to the agent, too https://github.com/ercole-io/ercole-agent/issues/161

**Comment by amreo** [comment]
UniqueName?

**Comment by cirelli94** [comment]
The problem is that when we have a RAC we will have:

```
Server srvpippo01:
dbname=PIPPO
dbuniquename=PIPPOPRD
Instance_name=PIPPO1
```
```
Server srvpippo02:
dbname=PIPPO
dbuniquename=PIPPOPRD
Instance_name=PIPPO2
```
So for /technologies?technology=Oracle/database&metrics=work return some names that differ, we should add that field.

**Comment by amreo** [comment]
InstanceNumber was added for that purpose

**Comment by cirelli94** [comment]
Sadly, InstanceName != dbName + InstanceName sometimes.
