### ISSUE TITLE
Add tests on marshal/unmarshal model structs

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#258]
Get all structs with reflection, marshal bust be == unmarshal

**Comment by cirelli94** [comment]
1. Fill struct with reflection
2. marshal struct to string
3. unmarshal string to new struct
4. check struct deep equals new struct

**Comment by amreo** [comment]
What is the exact purpose of this test?

**Comment by cirelli94** [comment]
The purpose of this test is to verify marshalling and unmarshalling of structs to test tags.

**Comment by cirelli94** [comment]
We should wait Go 2 for generics and use https://github.com/google/gofuzz

**Comment by cirelli94** [comment]
Not needed anymore.
