### ISSUE TITLE
[BUG] Fix chart-service routing

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#292]
Review chart-service routing to comply https://github.com/ercole-io/ercole/issues/244 card

**Comment by amreo** [comment]
???

**Comment by cirelli94** [comment]
"/technologies/oracle/database" should be "/technology=xxx&metrics=yyy" with "Oracle/database" as a param
"/technologies/changes" should be just "/changes"
"/technologies/types" should be "/type-of-technology"
