### ISSUE TITLE
[TECH] The json schema requires to be copied to model/hostdata_fe_schema_validator.go every time it's modified

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#297]
**How should be improved**
I think the schema should be read by ercole at runtime or be hardcoded/ inside the code using `go generate`

**Describe why ercole should be improved in this manner**
The reason is that the developers often forgot to update the string in model/hostdata_fe_schema_validator.go

**Comment by cirelli94** [comment]
Already done.
