### ISSUE TITLE
Use Hermes to send out nice email notifications

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#316]
**Is your feature request related to a problem? Please describe.**
No, just an aesthetic improvement

**Describe the solution you'd like**
Use https://github.com/matcornic/hermes to send emails

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amreo** [comment]
We should take in consideration that some times the sent email are parsed by automated systems.

**Comment by cirelli94** [comment]
When are Ercole  emails analyzed by automated systems?

**Comment by amreo** [comment]
When sysadmins/service desks want to trasform ercole emails into tickes

**Comment by anbrenna** [comment]
No longer required
