### ISSUE TITLE
Add filter on hostname for /alerts api 

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#333]
**Is your feature request related to a problem? Please describe.**
I need to filter alerts on hostname for the frontend

**Describe the solution you'd like**
I need a filter on `hostname` for `/alerts` api

**Describe alternatives you've considered**
To do this on frontend, but it's not nice

**Comment by amreo** [comment]
Remember that the Hostname can be NULL/the alerts can not have a hostname.

**Comment by cirelli94** [comment]
Won't do (for now).
