### ISSUE TITLE
 Database list page: add API for to merge all needed data

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#341]
**Is your feature request related to a problem? Please describe.**
FE, as it's now, should do 9 calls to BE

**Describe the solution you'd like**
Create a new API to merge all needed API for database list page

**Describe alternatives you've considered**
Make 9 calls from FE

**Additional context**
None

**Comment by amreo** [comment]
Required API:
* /hosts/technologies/databases (doesn't exist)
* /hosts/technologies/databases/total-work (doesn't exist)
* /hosts/technologies/databases/total-memory-size (doesn't exist)
* /hosts/technologies/databases/total-segment-size (doesn't exist)
* /hosts/technologies/databases/total-datafile-size (doesn't exist)
* /hosts/technologies/databases/types (doesn't exist) (or /hosts/technologies/databases/products?)
* /hosts/technologies/databases/environments (doesn't exist)
* /hosts/technologies/databases/archivelog-status (doesn't exist)
* /hosts/technologies/databases/disaster-recovery-status (doesn't exist)
* /hosts/technologies/databases/disaster-recovery-status (doesn't exist)
* /hosts/technologies/databases/high-reliability (doesn't exist)

**Comment by amreo** [comment]
The name of the API should be GET /frontend/database

**Comment by cirelli94** [comment]
Won't needed anymore.
