### ISSUE TITLE
[BUG] Change history values in cpuUsageHistory

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#343]
**Describe the bug**
Api `/hosts/{hostname}` return a field `history` with all data collected from agents.

**Expected behavior**
- `history` field should have a more talking name, like `cpuUsageHistory`
- We mustn't return all values, but just one value for a day, in fact this value collected is the mean of the previous day ( in fact it's always equal even if you run the agent multiple times ).
**- Consider change agent**

**To Reproduce**
Check vals in response

**Screenshots, logs, stdout, stderr, asciinema**
```

{"history":[
{"_id":"5f1ed520fbd36c3855aff598","createdAt":"2020-07-27T13:22:40.937Z","totalDailyCPUUsage":1.5},
{"_id":"5f1aaa2bfbd36c3855aff576","createdAt":"2020-07-24T09:30:19.32Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d61a4cb1ec248b08e33d5","createdAt":"2020-07-14T07:41:24.889Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d619dcb1ec248b08e33b9","createdAt":"2020-07-14T07:41:17.856Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d6179cb1ec248b08e339d","createdAt":"2020-07-14T07:40:41.161Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d6173cb1ec248b08e3381","createdAt":"2020-07-14T07:40:35.344Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d6168cb1ec248b08e3365","createdAt":"2020-07-14T07:40:24.931Z","totalDailyCPUUsage":1.5},
{"_id":"5f0d6161cb1ec248b08e332d","createdAt":"2020-07-14T07:40:17.23Z","totalDailyCPUUsage":1.5}
]}

```

**Comment by amreo** [comment]
The name history was choosen because it's generic. I suspect in the future will be added more  params that need to be graphed.
The second reason is because I want to know when past hostdata were sent.

PS:
> Check vals in response
aren't a reproduction steps.

**Comment by cirelli94** [comment]
We decided to mantain this data and do some more work in the frontend, to have more versatility for the future.
