### ISSUE TITLE
Add a API for getting oracle database page informations

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#347]
**Is your feature request related to a problem? Please describe.**
I want to get some informations about oracle databases without making 10 requests. 

**Describe the solution you'd like**
I want to have a single api /frontend/databases/oracle that return informations from these APIs: 
- [ ] /hosts/technologies/oracle/databases
- [ ] /hosts/technologies/oracle/databases/top-workload
- [ ] /hosts/technologies/oracle/databases/top-unused-instance-resource
- [ ] /hosts/technologies/oracle/databases/environments
- [ ] /hosts/technologies/oracle/databases/archivelog-status
- [ ] /hosts/technologies/oracle/databases/dataguard-status
- [ ] /hosts/technologies/oracle/databases/high-reliability
- [ ] /hosts/technologies/oracle/databases/versions
- [ ] /hosts/technologies/oracle/databases/platform (doesn't exist actually)

**Describe alternatives you've considered**
Make 10 API requests

**Additional context**
![Schermata del 2020-08-06 16-14-31](https://user-images.githubusercontent.com/12671924/89542438-f8431680-d7ff-11ea-9df7-1c51c63df411.png)

**Comment by cirelli94** [comment]
Already done.
