### ISSUE TITLE
Add support to license agreement

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#365]
**Is your feature request related to a problem? Please describe.**
I want to handle my license agreement in more detailed manner.

**Describe the solution you'd like**
Add support to license agreement.

**Describe alternatives you've considered**
None

**Additional context**
![Schermata del 2020-08-24 17-27-04](https://user-images.githubusercontent.com/12671924/91064050-0cc04500-e62f-11ea-9c54-51018953b844.png)

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole/issues/366

**Comment by amreo** [comment]
Depends on #367

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole/issues/368

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole/issues/369

**Comment by amreo** [comment]
Depends on #370

**Comment by amreo** [comment]
Depends on #371

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole-web/issues/210

**Comment by amreo** [comment]
Depends on https://github.com/ercole-io/ercole-web/issues/211

**Comment by amreo** [comment]
Depdnes on #374

**Comment by amreo** [comment]
Depends on #372

**Comment by amreo** [comment]
Depends on #375

**Comment by amreo** [comment]
Depends on #376

**Comment by amreo** [comment]
Depends on #377

**Comment by amreo** [comment]
Depends on #378 #379  #380  #381  #382

**Comment by cirelli94** [comment]
- [ ] Depends on #366
- [ ] Depends on #367
- [ ] Depends on #368
- [ ] Depends on #369
- [ ] Depends on #370
- [ ] Depends on #371
- [ ] Depends on ercole-io/ercole-web#210
- [ ] Depends on ercole-io/ercole-web#211
- [ ] Depends on #374
- [ ] Depends on #372
- [ ] Depends on #375
- [ ] Depends on #376
- [ ] Depends on #377
- [ ] Depends on #378 #379 #380 #381 #382
