### ISSUE TITLE
[TECH] Remove Count and Unlimited from LicenseCount struct and collection

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole#383]
**How should be improved**
Remove Count and Unlimited from model.LicenseCount struct; update LicenseCountBsonValidatorRules

**Describe why ercole should be improved in this manner**
After the implementation of #374 we will not need the save Count and Unlimited inside the licenses collection

**Comment by cirelli94** [comment]
There's no more LicenseCount in model
