### ISSUE TITLE
Add licenses in Oracle db when mounted by its primary db

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#433]
**Is your feature request related to a problem? Please describe.**
We can't known licenses really in use by an Oracle Db when is mounted.

**Describe the solution you'd like**
We can copy licenses in use by its primary db, of which we known the licenses, and which are the same in use by the mounted one.
To do so, we must match the primary (open db) with the secondary (mounted) by DbID and DbRole infos which we do not collect by now.

- We need to add DbID and DbRole informations in OracleDatabase model
- We need to add DbID and DbRole informations in OracleDatabase in swagger.yml
- We have to edit `db.sh` and `db.sql` to retrieve Id and Role and consequently edit agent
- We have to edit `dbmounted.sh` and `dbmounted.sql` to retrieve Id and Role and consequently edit agent
- We have to show this info collected in the frontend: in host detail page > in each db tab > Info > Db Details under `Status` field add both id and role

![image](https://user-images.githubusercontent.com/1636493/96700345-a25a2580-138f-11eb-9100-83c6e492cd4e.png)
- We must add the logic to copy licenses when secondary db hostdata arrive, some pseudocode for this:
```
if (db.status == MOUNTED && 
      ( db.Role == `PHYSICAL STANDBY` || db.Role == `LOGICAL STANDBY`) )
    // it's a secondary db, there should be its primary!

    // Find a DB that has equal DBID, equal NAME, that has db.Role PRIMARY, db.Status == OPEN
        If found:
            take the licenses enabled: if any licenses exist, enabled it in secondary with 
            count of each licenses = core (of the secondary ) * coreFactor
        else:
            throw new alert: category enginge, create a new code: "Missing primary database on standby database {dbname}"
```

**Describe alternatives you've considered**
Keep missing that licenses! :cry: 

**Additional context**
None.

**Comment by raffaelloferrari** [comment]
For ercole-agent I create pull request  **Add dbid and database role for #433 # 212** 
Fetcher `db.sh` and `dbmounted.sh` will return as second and third field `DBID `and `DBROLE`.
