### ISSUE TITLE
Add ability to change configuration from ercole-web

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#446]
**Is your feature request related to a problem? Please describe.**
Sometimes users need to change configuration files.

**Describe the solution you'd like**
Add a page in the FE to edit configurations.

**Describe alternatives you've considered**
Edit manually configuration files via filesystem on the server.

**Comment by StefaniaNorisSorint** [comment]
Wait information from business to create settings

**Comment by raffaelloferrari** [comment]
You have to take configuration from ercole.toml file and move it in database

**Comment by afumagalli98** [comment]
Depends on #1187 , https://github.com/ercole-io/ercole/issues/1187
