### ISSUE TITLE
There are some duplicate alerts

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#489]
**Problem**
When you go to Alerts, you will find many duplicates such as "The server XX was added tp ercole". 
The alert is recorded multiple times because we run the check once per day and unless the alert is marked as read/it's fixed, the system keeps tracking it.

Notes

- the column date refers to the timestamp of the alert being generated, not when the event actually happened. 
- some type of alerts cannot be solved/read as there is no check box to tick
- some type of alerts must be fixed (e.g. type agent / severity critical. In this case, it could make sense to keep the duplicates. 

Request
If alert severity = info, then duplicates should be ignored from the daily check as it does not add any value (es. the server was added to ercole)

If aert severity = critical, then duplicates are allowed as an action is required (es. no data received from the host)

In the dashboard / license chart, we should make sure that duplicates are not counted

**Comment by cirelli94** [comment]
Can't find any duplicate, nothing to fix here.
