### ISSUE TITLE
Task > Test integration with LDAP

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#501]
The integration has never been tested before

**Comment by amreo** [comment]
It was already tested by me...
https://github.com/ercole-io/ercole-docs/issues/68

**Comment by elisaroncalli** [comment]
Thanks @amreo 
@raffaelloferrari FYI this is done. Can we close the ticket?

**Comment by raffaelloferrari** [comment]
I don't find documentation on how to configure it in https://ercole.io

**Comment by raffaelloferrari** [comment]
@amreo have you produce documentation?

**Comment by amreo** [comment]
No, I never produced the documentation (that is the why the issue is still open)

**Comment by cirelli94** [comment]
Done.
