### ISSUE TITLE
Alert type=agents keep being generated after the hostname has been dismissed

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#502]
**Current situation**
Try to manually dismiss a hostname from Hosts > Host name > Dismiss
Wait for the daily check for the alert.
Then go to Alert > use advanced filter to sort by hostname dismissed
You will find related alerts type = agent despite the hostname has been dismissed / archived. 
(e.g. No data received from the host XX in the last (6) days )

**Expected behaviour**
WHEN a hostname is dismissed 
WHEN freshnesshCheckJob check for agents that are not sending data, 
AGENT - NO_DATA alerts for dismissed host must not be generated.

**Comment by cirelli94** [comment]
Doesn't happen, probably the problem was:
https://github.com/ercole-io/ercole/issues/531
