### ISSUE TITLE
Hosts > Agent > Last Update Date Format 

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#506]
**Problem**
GIVEN that I am a user logging in from UTC+1 (09:40 AM),
WHEN I go to Hosts>Agent to view when he last update occurred, 
I expect to view the date and time in my current local time, 
However, at the moment I view the date in time in ZULU / UTC format (8:40 AM)

yyyy-MM-dd'T'HH:mm:ss.SSS'Z
Ex: 2021-02-19T10:39:42.973Z

**Change request**
We have three options:

1) Display the UTC/ZULU format by default for all users. In this case we should add the timezone reference in the UI.
2) Display the local time and date of ercole server by default for all users. In this case we should add a reference in the UI so that the user is not confused.
3) Dinamically display the local time and date of the user logged in.

We recommend to display the local date and time of ercole server to all users. This represents a "system data" and not a "user related data".

**Dependencies**
Are there other places in the platform where we use a different criteria?
Should we keep consistency and use the same format across all pages?

**Comment by cirelli94** [comment]
Already done.
