### ISSUE TITLE
New API> Unused Thread for Hosts

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#510]
**Problem**
Go to Databases > Oracle > Databases > Top 3 unused instances
The thread utilization value taken from API /hosts/technologies/oracle/databases/top-reclaimable is wrong:

**Request**
- Change BE logic:
Given a hostname
IF            CPU count = max CPU = es 48
               Work = CPU used = es 1
THEN      Threat Used = CPU count - work = 48-1 = 47

The value displayed in the table must be equal to the value displayed in the top 3 unused instances box.
Also we should round up the value to 2 decimals

- Change FE label in: Thread Unused

**Comment by elisaroncalli** [comment]
As discussed, @raffaelloferrari 
In Top Unused instances, the value displayed in column "Thread Utilization" is actually the "Reclammable gigabyte"

![image](https://user-images.githubusercontent.com/79091396/109478767-f2ea3980-7a79-11eb-8fa3-11867c1a1e68.png)
Non thread utilization ma reclammable gigabyte

Please confirm if:
1) Keep the logic and update the wrong label
2) Keep the lable and update the logic

FYI @rcmaiolini @cirelli94

**Comment by cirelli94** [comment]
today we are using API `/hosts/technologies/oracle/databases/top-reclaimable`

**Comment by cirelli94** [comment]
Opened https://github.com/ercole-io/ercole-web/issues/283 .
