### ISSUE TITLE
BLOCKED> Wrong data > DB space utilization

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#511]
Note: in 2.0. we introduced pluggable databases (pdb)

**Problem**
Go to dev environment
Search host : oraexa0b.milXXXXXXX
In Database info > the space utilization values are wrong

In this example, 193 / 124 / 85 do not take into account the pluggabe databases 

Expected behaviour: the space utilization of a DB must include the space utilization of the pdb included in the CDB

**Comment by raffaelloferrari** [comment]
Create a space_pdb fetcher where we fetch segment_size datafile_size and Allocable_size 
Modify in case it's pdb don't take the normal segment_size datafile_size and Allocable_size values but replace them with the sum.

**Comment by cirelli94** [comment]
I moved this in QA if the investigation part is done @raffaelloferrari .
We'll open new issues as needed at sprint cerimony.
