### ISSUE TITLE
API to return ercole version

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#516]
**Request**
As a customer, when I log in to the platform, I want to see which Ercole version is installed.

**Benefits**
- Customers knows which version is installed
- We can track the level of adoption and make sure everyone is on the same version

Notes
Currently we can release back end and front end versions separately

We need to review our internal processes first (major releases, minor releases, hot fixes)

**Comment by cirelli94** [comment]
We have to add an api `/version` in the `api-service` that return [serverVersion](https://github.com/ercole-io/ercole/blob/014787be908f275bb56f454b0e84c22abdf91b57/cmd/root.go#L32) value that is modified by [agola, at build time](https://github.com/ercole-io/ercole/blob/014787be908f275bb56f454b0e84c22abdf91b57/.agola/config.jsonnet#L26).
I think this will need some changes :thinking:
