### ISSUE TITLE
Dashboard > Agents which do not send data > update logic

### ISSUE THREAD

**Issue by elisaroncalli** [ercole-io/ercole#517]
Each agent has a configurable parameter that determines how often it is run. The default value is 24 h

**Problem**
Go to Dashboard > Top right > "Agent which do not send data"
Here we currently display ALL agents that are not sending data in the last 24 hours.

**Change request**
We should update the logic and display only the list of Agents that are not running as per parameter.
E.g. 
Host x - parameter 24 h 
Host y - parameter 48 h 

(note: this requires a real time checking)

**Comment by cirelli94** [comment]
Closed, will be done in https://github.com/ercole-io/ercole/issues/766
