### ISSUE TITLE
When you dismiss a host a related alert is not deleted

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#531]
**Describe the bug**
If you find an alert related to a host and then you delete the host, the alert remain in the list.
If you click the hostname in the list of alerts a 404 error (page not fount) is displayed

**Fix and improvement**
WHEN dismiss agent set alerts.status = "DISMISSED" to others alert

Check that DISMISSED alerts can't be set to ACK or status changed.
When I receive a new hostdata from a dismissed host, leave DISMISSED alerts as they are.

**Comment by cirelli94** [comment]
I discussed this one a little bit with Ricardo and Raffaello and I tought that we should:
BE, WHEN dismiss agent:
- delete alert AGENT NO_DATA
- set alerts.status = "DISMISSED" to others alert

FE:
- If an alert.status is "DISMISSED", do not enable link on hostname

Some other questions:
When I receive a new hostdata from a dismissed host, should I leave DISMISSED alerts to NEW or ACK?

FE:
- DISMISSED alerts should be showed by default?
-  DISMISSED alerts can be set to ACK ( and so, add the checkbox in that column) ?
