### ISSUE TITLE
Edit API /hosts with url parameter "summary" to return needed values

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#550]
The actual implementation of Edit /hosts with url parameter "summary" was done before have the FE.

Now that we know exactly what the FE needs in the Hosts page we should edit this API to return only the needed data.
Among the other things:
- "features" should be only an array with the features enabled, instead of all the data
- return a []string "dbs" with the name of the databases

**Comment by cbiglioli** [comment]
Already implemented.
