### ISSUE TITLE
[BUG] /alerts/ack by ids: must check there are no duplicates

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#578]
**Describe the bug**

API /alerts/ack by ids receive duplicates ids and return 404 as the second time it try to acknoledge the same id, since it was just acknowledged, it fails. 

**Expected behavior**

Return a bad request error

**To Reproduce**

Call the API with duplicated id in ids array

**Comment by cbiglioli** [comment]
Already implemented.
