### ISSUE TITLE
Export xlsx from multiple APIs

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#582]
We need to be able to export data from these APIs used in these pages:
- hosts - /hosts
- Databases - /hosts/technologies/all/databases
- Oracle - /hosts/technologies/oracle/databases
- ADDM - /hosts/technologies/oracle/databases/addms
- Segment Advisors - /hosts/technologies/oracle/databases/segment-advisors
- Patch Advisor - /hosts/technologies/oracle/databases/patch-advisors
- MySql - /hosts/technologies/mysql/databases
- Hypervisors - /hosts/clusters
- ?? Clusters - /hosts/clusters/:clusterID
- ?? Engineered Systems - /hosts/technologies/oracle/exadata
- Alerts - /alerts
- Licenses Agreement:
- Oracle - /agreements/oracle/database
- MySql - /agreements/mysql/database
- Licenses Compliance - /hosts/technologies/all/databases/licenses-compliance
- Licenses Used - /hosts/technologies/all/databases/licenses-used (with two sheets: one for databases, one for hosts)

**Comment by uortizrodas** [comment]
- [x] hosts - /hosts
- [ ] Databases - /hosts/technologies/all/databases
- [ ] Oracle - /hosts/technologies/oracle/databases
- [ ] ADDM - /hosts/technologies/oracle/databases/addms
- [ ] Segment Advisors - /hosts/technologies/oracle/databases/segment-advisors
- [ ] Patch Advisor - /hosts/technologies/oracle/databases/patch-advisors
- [ ] MySql - /hosts/technologies/mysql/databases
- [ ] Hypervisors - /hosts/clusters
- [ ] ?? Clusters - /hosts/clusters/:clusterID
- [ ] ?? Engineered Systems - /hosts/technologies/oracle/exadata
- [ ] Alerts - /alerts
- [ ] Licenses Agreement:
- [ ] Oracle - /agreements/oracle/database
- [ ] MySql - /agreements/mysql/database
- [ ] Licenses Compliance - /hosts/technologies/all/databases/licenses-compliance
- [ ] Licenses Used - /hosts/technologies/all/databases/licenses-used (with two sheets: one for databases, one for hosts)

**Comment by cirelli94** [comment]
We need to keep the same columns name and order.

**Comment by cirelli94** [comment]
Done in #622
