### ISSUE TITLE
Add Cluster tab to License Used page 

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole#631]
Currently the license used page is composed of the databases and host tabs. 
It is necessary to add a new tab "Cluster" where clusters are listed with their licenses per cluster. 
The new table must have the fields
Cluster: name of the cluster to which the host belongs
Part Number
Description
Metric
Used Licenses: will be the sum of the cores of the cluster multiplied by the core factor
The new page should respect the standard and therefore have the advanced filters and the export button.

**Comment by cirelli94** [comment]
Replaced for the BE with #644
