### ISSUE TITLE
Wrong covered calculation when metric is Named User Plus Perpetual

### ISSUE THREAD

**Issue by cbiglioli** [ercole-io/ercole#735]
**Describe the bug**
In Licenses Compliance covered calculation is wrong where metric is Named User Plus Perpetual. Covered calculation is multiplied by 25 twice.

**Fix and improvement**
Remove * model.GetFactorByMetric(license.Metric) in api-service\service\oracle_database_license_types.go

**Comment by cirelli94** [comment]
Fixed by #739 for #734
