### ISSUE TITLE
Analyze "licenses used" and "licenses compliance" pages load times

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#791]
High load times were found opening the pages "Licenses Used" and "Licenses Compliance" when a lot of data needs to be shown

**Comment by rcmaiolini** [comment]
Dependency: https://github.com/ercole-io/ercole/issues/616

**Comment by cbiglioli** [comment]
momentarily in stand by

**Comment by cbiglioli** [comment]
No longer needed.
