### ISSUE TITLE
Implement a new API for SqlServer license-types

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole#910]
Import json file for the new collection:
ms_sqlserver_database_license_types
the collection must contain the following parameters

- _id (Part Number)
- itemDescription
- edition
- version

Add a new API:
 /api/settings/microsoft/database/license-types (GET)
to return data from the new collection

**Comment by afumagalli98** [comment]
@raffaelloferrari @capaaway is it possible to have the data to populate the collection?
